config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: [:update]

  resources :inventories, only: [:index, :show, :destroy, :new, :create] do
    get 'foods/new', to: 'inventory_foods#new'
    post 'foods', to: 'inventory_foods#create'
    delete 'foods/:id', to: 'inventory_foods#destroy', as: 'food'
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  get 'shopping_list', to: "shopping_list#index"

  # Defines the root path route ("/")
  root 'recipes#public_recipes'
end

app/models/inventory_food.rb
# frozen_string_literal: true

class InventoryFood < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :inventory
  belongs_to :food
end

app/controllers/inventory_foods_controller.rb
# frozen_string_literal: true

# InventoryFoodsController
class InventoryFoodsController < ApplicationController
  def new
    @user = current_user
    @inventory = Inventory.find_by_id(params[:inventory_id])
    @available_food = @user.foods
    @inventory_food = InventoryFood.new
  end

  def create
    @inventory = Inventory.find_by_id(params[:inventory_id])
    @inventory_food = InventoryFood.new(inventory_food_params.merge(inventory_id: @inventory.id))
    if @inventory_food.valid?
      @inventory_food.save
      redirect_to inventory_path(@inventory.id), flash: { notice: 'Food created successfully.' }
    else
      render :new
    end
  end

  def destroy
    @inventory_food = InventoryFood.find_by_id(params[:id])
    @inventory_food.destroy
    redirect_to inventory_path(params[:inventory_id]), flash: { notice: 'Item deleted.' }
  end

  private

  def inventory_food_params
    params.require(:inventory_food).permit(:quantity, :food_id)
  end
end

app/helpers/inventory_foods_helper.rb
# frozen_string_literal: true

# InventoryFoodsHelper
module InventoryFoodsHelper
end

app/views/inventory_foods/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">New Inventory Item</h1>
  <div class="mt-14">
    <%= form_with model: @inventory_food, url: inventory_foods_path(@inventory.id), local: true, html: {"data-turbo": "false"} do |form| %>
      <% if @inventory_food.errors.any? %>
        <div class="border px-7 py-3 mb-4 border-red-400 bg-red-200 font-medium">
          <% @inventory_food.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
        </div>
      <% end %>
      <div class="border p-7 flex flex-col gap-7">
        <div>
          <%= form.label :quantity, class: 'font-medium block mb-2' %>
          <%= form.number_field :quantity, class: 'border rounded' %>
        </div>
        <div>
          <%= form.label :food_id, class: 'font-medium block mb-2' %>
          <%= form.select :food_id, options_from_collection_for_select(@available_food, "id", "name"), {}, { class: "border rounded" } %>
        </div>
        <%= form.submit "Submit", class: 'text-sm px-4 py-2 bg-transparent hover:bg-teal-500 text-teal-700 max-w-fit font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded' %>
        <div>
          <p>
            Food is not in the list? Add one <%= link_to 'here', new_food_path, class: "text-teal-500 hover:text-teal-700" %>.
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>