config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: [:update]

  resources :inventories, only: [:index, :show, :destroy, :new, :create] do
    get 'foods/new', to: 'inventory_foods#new'
    post 'foods', to: 'inventory_foods#create'
    delete 'foods/:id', to: 'inventory_foods#destroy', as: 'food'
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  get 'shopping_list', to: "shopping_list#index"

  # Defines the root path route ("/")
  root 'recipes#public_recipes'
end

app/models/inventory.rb
# frozen_string_literal: true

class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :foods, through: :inventory_foods
  validates :name, presence: true
end

app/controllers/inventories_controller.rb
# frozen_string_literal: true

# InventoriesController
class InventoriesController < ApplicationController
  def index
    @user = current_user
    @inventories = @user.inventories unless @user.nil?
  end

  def show
    @inventory = Inventory.find_by_id(params[:id])
  end

  def destroy
    @inventory = Inventory.find_by_id(params[:id])
    @inventory.destroy
    redirect_to inventories_path
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @user = current_user
    @inventory = Inventory.new(inventory_params.merge(user_id: @user.id))
    if @inventory.valid?
      @inventory.save
      redirect_to inventories_path
    else
      render :new
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name)
  end
end

app/helpers/inventories_helper.rb
# frozen_string_literal: true

# InventoriesHelper
module InventoriesHelper
end

app/views/inventories/index.html.erb
<div class="w-full">
  <div class="flex flex-wrap justify-between items-baseline gap-7 mb-6">
    <h1 class="font-bold text-4xl">Your Inventories</h1>
    <% if user_signed_in? %>
      <%= 
        link_to "New inventory",
        new_inventory_path,
        class: "text-sm px-4 py-2 leading-none bg-transparent hover:bg-teal-500 text-teal-700 justify-center font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded"
      %>
    <% end %>
  </div>
  <% if @inventories.empty? %>
    <p class="border p-7 border-yellow-400 bg-yellow-200 font-medium">You don't have any inventories.</p>
  <% else %>
    <div class="flex flex-col gap-7"> 
      <% @inventories.each do |inventory| %>
        <div class="border rounded border-gray-400 p-7 font-bold text-xl flex justify-between items-baseline">
          <%= link_to inventory.name, inventory_path(inventory.id) , class: "hover:text-teal-700" %>
          <%= 
            button_to "Delete", 
            inventory_path(inventory.id), method: :delete,
            class: "text-sm px-4 py-2 leading-none bg-transparent hover:bg-red-500 text-red-700 justify-center font-semibold hover:text-white border border-red-500 hover:border-transparent rounded"
          %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/inventories/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">New Inventory</h1>
  <div class="mt-14">
    <%= form_with model: @inventory, url: inventories_path, local: true, html: {"data-turbo": "false"} do |form| %>
      <% if @inventory.errors.any? %>
        <div class="border px-7 py-3 mb-4 border-red-400 bg-red-200 font-medium">
          <% @inventory.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
        </div>
      <% end %>
      <div class="border p-7 flex flex-col gap-7">
        <div>
          <%= form.label :name, class: 'font-medium block mb-2' %>
          <%= form.text_field :name, class: 'border rounded' %>
        </div>
        <%= form.submit "Submit", class: 'text-sm px-4 py-2 bg-transparent hover:bg-teal-500 text-teal-700 max-w-fit font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/inventories/show.html.erb
<div class="w-full">
  <header class="flex flex-wrap justify-between items-baseline gap-7">
    <h1 class="font-bold text-4xl">
      <%= @inventory.name %>
    </h1>
    <%=
      link_to "Add food", inventory_foods_new_path(@inventory.id),
      class: "text-sm px-4 py-2 leading-none bg-transparent hover:bg-teal-500 text-teal-700 justify-center font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded"
    %>
  </header>
  <div class="mt-6 relative md:overflow-hidden overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm rounded text-center">
      <thead class="text-white">
        <tr class="bg-teal-700">
          <th class="px-4 py-2">Food</th>
          <th class="px-4 py-2">Quantity</th>
          <th class="px-4 py-2">Actions</th>
        </tr>
      </thead>
      <tbody class="text-center">
        <% @inventory.inventory_foods.each do |item| %>
          <tr>
            <td class="border px-4 py-2">
              <%= item.food.name %>
            </td>
            <td class="border px-4 py-2">
              <%= "#{item.quantity} #{item.food.measurement_unit}" %>
            </td>
            <td class="border px-4 py-2">
              <%=
                button_to "Delete", inventory_food_path(@inventory.id, item.id), method: :delete,
                class: "text-sm px-4 py-2 leading-none bg-transparent hover:bg-red-500 text-red-700 justify-center font-semibold hover:text-white border border-red-500 hover:border-transparent rounded"
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>