config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: [:update]

  resources :inventories, only: [:index, :show, :destroy, :new, :create] do
    get 'foods/new', to: 'inventory_foods#new'
    post 'foods', to: 'inventory_foods#create'
    delete 'foods/:id', to: 'inventory_foods#destroy', as: 'food'
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  get 'shopping_list', to: "shopping_list#index"

  # Defines the root path route ("/")
  root 'recipes#public_recipes'
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :public, inclusion: { in: [true, false] }
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

# RecipesController
class RecipesController < ApplicationController
  before_action :fetch_recipe, only: %i[show destroy toogle_public]

  def index
    @current_user = current_user
    if @current_user.nil?
      redirect_to user_session_path, flash: { alert: 'You must be signed in to continue.' }
    else
      @recipes = @current_user.recipes
    end
  end

  def show
    @recipe = Recipe.find_by_id(params[:id])
    @recipe_foods = @recipe&.recipe_foods
    @recipe = 'No recipes' if @recipe.nil?
    @current_user = current_user
    @inventories = current_user&.inventories
  end

  def new
    @recipe = Recipe.new
    @foods = Food.all
    @recipe.recipe_foods.build
  end

  def create
    @recipe = Recipe.new(recipe_params.merge(user: current_user))
    if @recipe.save
      flash[:success] = 'Recipe created.'
      redirect_to recipe_path(@recipe.id)
    else
      flash[:fail] = 'Recipe creation unsucessful.'
    end
  end

  def destroy
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.user == current_user
      if @recipe.destroy
        flash[:success] = 'Recipe deleted.'
      else
        flash[:fail] = 'Recipe deletion unsucessful.'
      end
    end
    redirect_to recipes_path
  end

  def toogle_public
    @recipe = fetch_recipe
    @recipe.public = !@recipe.public
    text = 'private'
    text = 'public' if @recipe.public
    if @recipe.save
      flash[:success] = "#{@recipe.name} is now #{text}!"
    else
      flash[:fail] = @recipe.public
    end
    redirect_to recipe_path(@recipe.id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  private

  def fetch_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

# RecipesHelper
module RecipesHelper
  def count_items(obj)
    obj.count
  end

  def total_price(recipe)
    sum = 0
    recipe.recipe_foods&.each { |i| sum += i.quantity * i.food.price }
    sum
  end
end

app/views/recipes/_recipe_food.html.erb
<tr>
  <td class="border px-4 py-2"> <%= recipe_food.food.name %></td>
  <td class="border px-4 py-2"><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
  <td class="border px-4 py-2"><%= recipe_food.food.price * recipe_food.quantity %></td>
  <% if recipe_food.recipe.user == current_user %>
    <td class="border px-4 py-2 ">
      <div class="flex flex-row justify-around min-h-full gap-2">
        <%= link_to "Remove", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.id), data: { "turbo-method": :delete }, class: "flex bg-transparent text-sm hover:bg-red-500 text-red-700 justify-center font-semibold hover:text-white p-1 px-4 border border-red-500 hover:border-transparent rounded"%>
      </div>
    </td>
  <% end %>
</tr>

app/views/recipes/index.html.erb
<div class="flex flex-col container mx-auto min-w-full">
  <div class="flex justify-between items-baseline mb-6">
    <h1 class="font-bold text-4xl"> <%= @current_user.name %>'s Recipes</h1>
    <% if user_signed_in? %>
      <%= 
        link_to "New Recipe", 
        new_recipe_path,
        class: "text-sm px-4 py-2 leading-none bg-transparent hover:bg-teal-500 text-teal-700 justify-center font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded"
      %>
    <% end %>
  </div>
  <% if @recipes.empty? %>
    <p class="border p-7 border-yellow-400 bg-yellow-200 font-medium">You don't have any recipes.</p>
  <% else %>
    <%= render partial: "shared/recipe", collection: @recipes %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">New Recipe</h1>
  <div class="mt-14">
    <%= form_with model: @recipe, url: recipes_path, local: true, html: {"data-turbo": "false"} do |form| %>
      <% if @recipe.errors.any? %>
        <div class="border px-7 py-3 mb-4 border-red-400 bg-red-200 font-medium">
          <% @recipe.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
        </div>
      <% end %>
      <div class="border p-7 flex flex-col gap-7">
        <div>
          <%= form.label :name, class: 'font-medium block mb-2' %>
          <%= form.text_field :name, class: 'border rounded' %>
        </div>
        <div>
          <%= form.label :preparation_time, class: 'font-medium block mb-2' %>
          <%= form.number_field :preparation_time, class: 'border rounded', placeholder: 'In minutes' %>
        </div>
        <div>
          <%= form.label :cooking_time, class: 'font-medium block mb-2' %>
          <%= form.number_field :cooking_time, class: 'border rounded', placeholder: 'In minutes' %>
        </div>
        <div>
          <%= form.label :description, class: 'font-medium block mb-2' %>
          <%= form.text_area :description, class: 'border rounded' %>
        </div>
        <div>
          <%= form.label :public, class: 'form-check-label'%>
          <%= form.check_box :public , class: 'form-check-input'%>
        </div>
        <%= form.submit "Submit", class: 'text-sm px-4 py-2 bg-transparent hover:bg-teal-500 text-teal-700 max-w-fit font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="flex flex-col container mx-auto min-w-full">
  <h1 class="font-bold text-4xl mb-6">All Recipes</h1>
  <% if @recipes.empty? %>
    <p class="border p-7 border-yellow-400 bg-yellow-200 font-medium">No public recipes.</p>
  <% else %>
    <%= render partial: "shared/public_recipe", collection: @recipes %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="flex-col min-w-full" x-data="{ open: false }">
  <% if @recipe == 'No recipes' %>
    <h2>Invalid link!</h2>
  <% elsif @recipe.public || @recipe.user == @current_user %>
    <h1 class="text-gray-900 font-bold text-center text-3xl my-8"> <%=  @recipe.name %> </h1>
    <div class="w-full border border-gray-400 bg-white rounded p-4 flex flex-col justify-between leading-normal">
      <div class="max-w-sm w-full min-w-full lg:max-w-full flex mb-4">
        <div class="sm:w-full md:w-2/3 p-4 flex flex-col justify-center leading-normal">
          <h3 class="my-2 text-gray-700 font-bold">Preparation Time: <%= @recipe.preparation_time/60 %> hours <%= @recipe.preparation_time%60 %> minutes</h3>
          <h3 class="my-2 text-gray-700 font-bold">Cooking Time: <%= @recipe.cooking_time/60 %> hours <%= @recipe.cooking_time%60 %> minutes</h3>
        </div>
        <div class="sm:w-full md:w-1/3 p-4 flex flex-col justify-center leading-normal">
          <% if @recipe.user == @current_user %>
            <div class="flex items-center justify-center w-full mb-12">
              <%= button_to toogle_public_path(@recipe.id), method: :patch do %>
                <label for="toogleA" class="flex items-center cursor-pointer">
                  <!-- toggle -->
                  <div class="relative">
                    <!-- input -->
                    <input id="toogleA" type="checkbox" class="sr-only" <%='checked' if @recipe.public %>/>
                    <!-- line -->
                    <div class="w-10 h-4 bg-gray-400 rounded-full shadow-inner"></div>
                    <!-- dot -->
                    <div class="dot absolute w-6 h-6 bg-white rounded-full shadow -left-1 -top-1 transition"></div>
                  </div>
                  <!-- label -->
                  <div class="ml-3 text-gray-700 font-medium">
                    Public
                  </div>
                </label>
              <% end %>
            </div>
            <%= button_to "Remove", recipe_path(@recipe.id), method: :delete, class: "flex mx-auto bg-transparent hover:bg-red-500 text-red-700 justify-center font-semibold hover:text-white p-1 w-40 border border-red-500 hover:border-transparent rounded"%>
          <% end %>
        </div>
      </div>
      <p class="text-gray-700 text-base p-4"><%= @recipe.description %></p>
    </div>
    <div class="w-full bg-white rounded p-4 flex flex-row justify-between leading-normal gap-2">
      <% if user_signed_in? %>
        <button type="" class="flex bg-transparent hover:bg-teal-500 text-teal-700 justify-center font-semibold hover:text-white p-1 px-4 border border-teal-500 hover:border-transparent rounded" @click="open = true">Generate Shopping List</button>
      <% end %>
      <% if @recipe.user == @current_user %>
        <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe.id), class: "flex bg-transparent hover:bg-lime-500 text-lime-700 justify-center text-center font-semibold hover:text-white p-1 px-4 border border-lime-500 hover:border-transparent rounded"%>
      <% end %>
    </div>
    <div class="mt-6 relative md:overflow-hidden overflow-x-auto shadow-md sm:rounded-lg">
      <table class="w-full text-sm rounded">
        <thead class="text-white">
          <tr class="bg-teal-700">
            <th class="px-4 w-5/12 py-2">Food</th>
            <th class="px-4 w-2/12 py-2">Quantity</th>
            <th class="px-4 w-2/12 py-2">Value</th>
            <% if @recipe.user == current_user %>
              <th class="px-4 w-3/12 py-2">Action</th>
            <% end %>
          </tr>
        </thead>
        <tbody><%= render partial:"recipe_food", collection: @recipe_foods %>
        </table>
      </div>
      <% if user_signed_in? %>
        <div class="absolute top-0 left-0 flex items-center justify-center w-full h-full" style="background-color: rgba(0,0,0,.5);" x-show="open">
          <%= render partial:"shared/shopping_list_form" %>
        </div>
      <% end %>
    <% else %>
      <h2>You are not authorized to view this recipe!</h2>
    <% end %>
  </div>