config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, except: [:update]

  resources :inventories, only: [:index, :show, :destroy, :new, :create] do
    get 'foods/new', to: 'inventory_foods#new'
    post 'foods', to: 'inventory_foods#create'
    delete 'foods/:id', to: 'inventory_foods#destroy', as: 'food'
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  get 'shopping_list', to: "shopping_list#index"

  # Defines the root path route ("/")
  root 'recipes#public_recipes'
end

app/views/shared/_navbar.html.erb
<nav
  class="flex items-center justify-between flex-wrap bg-teal-700 p-6"
  x-data="{ isOpen: false }"
  @keydown.escape="isOpen = false"
  @click.away="isOpen = false"
  :class="{ 'shadow-lg bg-teal-900' : isOpen , 'bg-teal-700' : !isOpen}"
>
  <%= link_to root_path, class: "flex items-center flex-shrink-0 text-white mr-6" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="fill-current h-8 w-8 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.656 7.343A7.975 7.975 0 0120 13a7.975 7.975 0 01-2.343 5.657z" />
      <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 16.121A3 3 0 1012.015 11L11 14H9c0 .768.293 1.536.879 2.121z" />
    </svg>
    <span class="font-semibold text-xl tracking-tight">Recipes</span>
  <% end %>
  <div class="block lg:hidden">
    <button
        @click="isOpen = !isOpen"
        type="button"
        class="block lg:hidden px-2 text-slate-200 hover:text-white focus:outline-none focus:text-white"
        :class="{ 'transition transform-180': isOpen }"
      >
        <svg
          class="h-6 w-6 fill-current"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
        >
          <path
            x-show="isOpen"
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0 1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828 4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z"
          />
          <path
            x-show="!isOpen"
            fill-rule="evenodd"
            d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"
          />
        </svg>
      </button>
  </div>
  <div
    class="w-full flex-grow lg:flex lg:items-center lg:w-auto"
    :class="{ 'block shadow-3xl': isOpen, 'hidden': !isOpen }"
  >
    <div class="text-sm lg:flex-grow">
      <%= link_to "Recipes", public_recipes_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
      <% if user_signed_in? %>
        <%= link_to "My Recipes", recipes_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Foods", foods_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Inventories", inventories_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
      <% end %>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
      <% else %>
        <%= link_to "Sign In", user_session_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_public_recipe.html.erb
<div class="max-w-sm w-full min-w-full lg:max-w-full flex mb-4">
  <div class="w-1/3 border border-r-0 border-gray-400 bg-white rounded-l p-4 flex flex-col justify-between leading-normal">
    <%= link_to public_recipe.name, recipe_path(public_recipe.id), class: "text-gray-900 font-bold text-xl mb-2" %>
    <h3 class="text-gray-900 font-bold"> <%= public_recipe.user.name %> </h3>
  </div>
  <div class="w-2/3 border border-l-0 border-gray-400 bg-white rounded-r p-4 flex flex-col justify-between leading-normal">
    <p class="text-gray-700 text-base">Total food items: <%= count_items(public_recipe.foods)%> </p>
    <p class="text-gray-700 text-base">Total food items: $<%= total_price(public_recipe)%> </p>
  </div>
</div>

app/views/shared/_recipe.html.erb
<div class="max-w-xs w-full min-w-full lg:max-w-full flex mb-4">
  <div class="w-1/3 border border-r-0 border-gray-400 bg-white rounded-l p-4 flex flex-col justify-between leading-normal">
    <%= link_to recipe.name, recipe_path(recipe.id), class: "text-gray-900 font-bold text-xl mb-2" %>
    <%= button_to "Delete", recipe_path(recipe.id), method: :delete, class: "flex bg-transparent hover:bg-red-500 text-red-700 justify-center text-sm font-semibold hover:text-white p-1 w-20 border border-red-500 hover:border-transparent rounded"%>
  </div>
  <div class="w-2/3 border border-l-0 border-gray-400 bg-white rounded-r p-4 flex flex-col justify-between leading-normal">
    <% if recipe.public %>
      <p class="text-sm text-gray-600 flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="fill-current text-gray-500 w-3 h-3 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
        </svg>
        Public
      </p>
    <% else %>
      <p class="text-sm text-gray-600 flex items-center">
        <svg class="fill-current text-gray-500 w-3 h-3 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
          <path d="M4 8V6a6 6 0 1 1 12 0v2h1a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-8c0-1.1.9-2 2-2h1zm5 6.73V17h2v-2.27a2 2 0 1 0-2 0zM7 6v2h6V6a3 3 0 0 0-6 0z" />
        </svg>
        Private
      </p>
    <% end %>
    <p class="text-gray-700 text-base"><%= recipe.description %></p>
  </div>
</div>

app/views/shared/_shopping_list_form.html.erb
<div class="border p-7 bg-white rounded" @click.away="open = false">
  <%= form_with url: shopping_list_path, method: :get, local: true, html: {"data-turbo": "false"} do |form| %>
    <div class="flex flex-col gap-7 p-5">
      <h1 class="font-bold text-4xl">New Shopping List</h1>
      <div class="hidden">
        <%= form.label :recipe_id, class: 'font-medium block mb-2' %>
        <%= form.text_field :recipe_id, value: @recipe.id %>
      </div>
      <div>
        <%= form.label :inventory_id, class: 'font-medium block mb-2' %>
        <%= form.select :inventory_id, options_from_collection_for_select(@inventories, "id", "name"), {}, { class: "border rounded" } %>
      </div>
      <%= form.submit "Submit", class: 'flex bg-transparent hover:bg-teal-500 text-teal-700 justify-center font-semibold hover:text-white p-1 px-4 border border-teal-500 hover:border-transparent rounded' %>
    </div>
  <% end %>
</div>